#define BASE_1_4 LT(_ART_MAC,KC_BSPC)
#define BASE_1_3 KC_T
#define BASE_1_2 KC_E
#define BASE_1_1 KC_N
#define BASE_2_4 LT(_ART_NAV,KC_D)
#define BASE_2_3 KC_K
#define BASE_2_2 KC_A
#define BASE_2_1 LT(_ART_CUS,KC_I)
#define BASE_3_4 LT(_ART_NUM,KC_MINS)
#define BASE_3_3 KC_P
#define BASE_3_2 KC_F
#define BASE_3_1 LT(_ART_PUNC,KC_C)
#define NUM_1_4 KC_CALC
#define NUM_1_3 KC_7
#define NUM_1_2 KC_8
#define NUM_1_1 KC_9
#define NUM_2_4 KC_0
#define NUM_2_3 KC_4
#define NUM_2_2 KC_5
#define NUM_2_1 KC_6
#define NUM_3_4 KC_COMM
#define NUM_3_3 KC_1
#define NUM_3_2 KC_2
#define NUM_3_1 KC_3
#define PUNC_1_4 KC_AT
#define PUNC_1_3 KC_HASH
#define PUNC_1_2 KC_AMPR
#define PUNC_1_1 KC_BSLS
#define PUNC_2_4 KC_DLR
#define PUNC_2_3 KC_COLN
#define PUNC_2_2 KC_SCLN
#define PUNC_2_1 KC_PERC
#define PUNC_3_4 KC_DQUO
#define PUNC_3_3 KC_LPRN
#define PUNC_3_2 KC_RPRN
#define PUNC_3_1 KC_TRNS
#define CUS_1_4 KC_TRNS
#define CUS_1_3 KC_MPRV
#define CUS_1_2 KC_MNXT
#define CUS_1_1 KC_TRNS
#define CUS_2_4 KC_MPLY
#define CUS_2_3 KC_MUTE
#define CUS_2_2 KC_VOLU
#define CUS_2_1 KC_TRNS
#define CUS_3_4 KC_TRNS
#define CUS_3_3 KC_MYCM
#define CUS_3_2 KC_VOLD
#define CUS_3_1 KC_TRNS
#define MOU_1_4 KC_TRNS
#define MOU_1_3 KC_WH_U
#define MOU_1_2 KC_MS_U
#define MOU_1_1 KC_WH_D
#define MOU_2_4 KC_BTN1
#define MOU_2_3 KC_MS_L
#define MOU_2_2 KC_MS_D
#define MOU_2_1 KC_MS_R
#define MOU_3_4 KC_BTN3
#define MOU_3_3 KC_WH_L
#define MOU_3_2 KC_WH_R
#define MOU_3_1 KC_BTN2
#define NAV_1_4 KC_ESC
#define NAV_1_3 KC_PGUP
#define NAV_1_2 KC_UP
#define NAV_1_1 KC_PGDN
#define NAV_2_4 KC_TRNS
#define NAV_2_3 KC_LEFT
#define NAV_2_2 KC_DOWN
#define NAV_2_1 KC_RIGHT
#define NAV_3_4 KC_CAPS
#define NAV_3_3 KC_PSCR
#define NAV_3_2 KC_END
#define NAV_3_1 KC_HOME
#define FUNC_1_4 KC_F1
#define FUNC_1_3 KC_F2
#define FUNC_1_2 KC_F3
#define FUNC_1_1 KC_F4
#define FUNC_2_4 KC_F5
#define FUNC_2_3 KC_F6
#define FUNC_2_2 KC_F7
#define FUNC_2_1 KC_F8
#define FUNC_3_4 KC_F9
#define FUNC_3_3 KC_F10
#define FUNC_3_2 KC_F11
#define FUNC_3_1 KC_F12